#pragma once

#define MAX_BUFF_SIZE 272

#define HEADER_COMMAND 0
#define HEADER_DATA_TYPE 1


#define SIZE_HEADER  2
#define SIZE_GID  10
#define SIZE_PIN  4

#define SIZE_BODY_DATA 85


#define COMMAND_CLIENT_UPDATE 2

#define COMMAND_CLIENT_READ 3
#define COMMAND_CLIENT_READ_NAME 0
#define COMMAND_CLIENT_READ_BIRTHDAY 1
#define COMMAND_CLIENT_READ_BALANCE 2

#define COMMAND_CLIENT_LOGOUT 4
#define COMMAND_CLIENT_LOGIN 5


#define COMMAND_SERVER_LOGIN_NG 0
#define COMMAND_SERVER_LOGIN_OK 1
#define COMMAND_SERVER_LOGIN_OK_RW 0
#define COMMAND_SERVER_LOGIN_OK_RO 1
