#pragma once

#define MAX_BUFF_SIZE 272
#define NUM_CANMA 5
#define NUM_NEWLINE_CHAR 1
//ヘッダーは含まない、カンマと改行文字
#define SIZE_DATA_LINE (MAX_BUFF_SIZE - SIZE_HEADER + NUM_CANMA + NUM_NEWLINE_CHAR)

#define HEADER_COMMAND 0
#define HEADER_DATA_TYPE 1

//const char* STR_NAME = "name";
//const char* STR_BIRTH = "birth";
//const char* STR_MONEY = "money";

#define SIZE_HEADER  2
#define SIZE_GID  10
#define SIZE_PIN  4

#define SIZE_BODY_DATA 85


#define COMMAND_CLIENT_UPDATE 2

#define COMMAND_CLIENT_READ 3
#define COMMAND_CLIENT_READ_NAME 0
#define COMMAND_CLIENT_READ_BIRTHDAY 1
#define COMMAND_CLIENT_READ_BALANCE 2

#define COMMAND_CLIENT_LOGOUT 4
#define COMMAND_CLIENT_LOGIN 5


#define COMMAND_SERVER_LOGIN_NG 0
#define COMMAND_SERVER_LOGIN_OK 1
#define COMMAND_SERVER_LOGIN_OK_RW 0
#define COMMAND_SERVER_LOGIN_OK_RO 1
